# Configuración de constantes del juego.

BOARD_SIZE =(255, 255)

PLAYER_LIVES = 4
PLAYER_SPEED = 5
DISPARO_SPEED = 9

ENEMIGOS1_LIVES = 1
ENEMIGOS2_LIVES = 2
ENEMIGOS1_SPEED = 2
ENEMIGOS2_SPEED = 3
